name: project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  webview_flutter: ^4.8.0
  get_it: ^7.7.0
  connectivity_plus: ^6.0.3
  page_transition: ^2.1.0
  flutter_lints: ^3.0.0
  package_info_plus: ^8.0.0
  percent_indicator: ^4.2.3

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Regular.otf
          weight: 400
        - asset: fonts/Satoshi-Medium.otf
          weight: 500
        - asset: fonts/Satoshi-Bold.otf
          weight: 700

  uses-material-design: true
  generate: true

